<a href="https://colab.research.google.com/github/Iam-whizzy/DataScience/blob/main/textTospeechspeechtoText.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
# Speech to text
# Text to Speech
# Deep Learning - branch of machine learning where machines learns from complex data (image, speech, video)
# Machine Learning -> Branch in AI where machines are trained to learn from data(classification - text, regression - numbers, clustering)
# Hugging Face - pretrained models
# gTTS -> googleTextToSpeech - Google Library

In [39]:
!pip install GTTS

In [40]:
from gtts import gTTS

In [41]:
text = "Jaywalker seems like a word that must have originated in New York City, since so many pedestrians of that metropolis seem to have no regard for crossing the street at the appointed time or place. Its place of birth is actually far from New York: the word appears to come from Kansas, or at least that is where we first see evidence of it in written use. Many of the other things we might think about jaywalker are similarly other than we might suppose."

language = 'en'

In [42]:
speech = gTTS(text = text, lang = language, slow = False)
speech.save('speech.mp3')

In [43]:
from IPython.display import Audio, display
sound_file = 'speech.mp3'
sound = Audio(sound_file, autoplay = True)
display(sound)

In [44]:
# Speech to text - Facebook
# Wav2Vec, Wav2Vec2Tokenizor
# Managing the audio sound
# Advanced audio processing
# Pre-Trained Model (Speech to Text)

import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

In [45]:
audio, rate = librosa.load('speech.mp3', sr = 16000)
print(audio)
print(rate)

[0. 0. 0. ... 0. 0. 0.]
16000


In [46]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/Wav2Vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:733: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


In [48]:
model = Wav2Vec2ForCTC.from_pretrained("facebook/Wav2Vec2-base-960h")

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/Wav2Vec2-base-960h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/Wav2Vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You sho

In [50]:
# breaking down audio to tensors

input_values = tokenizer(audio, return_tensors="pt").input_values

print(input_values)

tensor([[0.0019, 0.0019, 0.0019,  ..., 0.0019, 0.0019, 0.0019]])


In [52]:
#probability value that we can generate from our tensor values

logits = model(input_values).logits
logits


tensor([[[ 15.6112, -27.6951, -27.3099,  ...,  -6.9344,  -7.5953,  -8.1222],
         [ 15.5951, -27.7272, -27.3438,  ...,  -6.9429,  -7.6396,  -8.0896],
         [ 15.6353, -28.0910, -27.7298,  ...,  -6.7866,  -8.1195,  -8.0971],
         ...,
         [ 15.5621, -27.3755, -27.0005,  ...,  -6.3425,  -6.9324,  -7.6574],
         [ 15.6783, -27.5162, -27.1278,  ...,  -6.3897,  -7.1921,  -7.8316],
         [ 15.6743, -27.7106, -27.3175,  ...,  -6.6792,  -7.4607,  -8.0241]]],
       grad_fn=<ViewBackward0>)

In [54]:
prediction = torch.argmax(logits, dim = -1)
prediction

tensor([[0, 0, 0,  ..., 0, 0, 0]])

In [56]:
text = tokenizer.batch_decode(prediction)
text

['JAY WALKER SEEMS LIKE A WORD THAT MUST HAVE ORIGINATED IN NEW YORK CITY SINCE SO MANY PEDESTRIANS OF THAT METROPOLIS SEEM TO HAVE NO REGARD FOR CROSSING THE STREET AT THE APPOINTED TIME OR PLACE ITS PLACE OF BIRTH IS ACTUALLY FAR FROM NEW YORK THE WORD APPEARS TO COME FROM KANSAS OR AT LEAST THAT IS WHERE WE FIRST SEE EVIDENCE OF IT IN RIDDEN USE MANY OF THE OTHER THINGS WE MIGHT THINK ABOUT JAY WALKER OR SIMILARLY OTHER THAN WE MIGHT SUPPOSE']